CREATE TABLE "user" (
  ID                   		 SERIAL PRIMARY KEY,
	DEFAULT_COMPANY_CODE     VARCHAR(10)  NOT NULL,
	EMAIL 					         VARCHAR(200) UNIQUE NOT NULL,
	COMPLETE_NAME            VARCHAR(200),
	PASSWORD						     VARCHAR(500),
	RESET_PASSWORD			     BOOLEAN,
	LAST_PASSWORD_RESET_DATE INTEGER, 
	EXPIRATION_DATE			     INTEGER,
	CREATION_DATE            INTEGER,
	LAST_CHANGE_DATE         INTEGER,
	CONSTRAINT FK_USER_COMPANY_CODE FOREIGN KEY (DEFAULT_COMPANY_CODE)
		REFERENCES COMPANY (CODE)
);