CREATE TABLE COMPANY (
  ID               SERIAL PRIMARY KEY,
	CODE             VARCHAR(10) UNIQUE NOT NULL,
	NAME             VARCHAR(100),
	SITE_URL         VARCHAR(200),
	CREATION_DATE    INTEGER,
	LAST_CHANGE_DATE INTEGER
);